@echo off
adb shell pm install-existing com.miui.daemon
adb shell pm install-existing com.android.updater
adb shell pm install-existing com.miui.powerkeeper
adb shell pm install-existing com.miui.tsmclient
adb shell pm install-existing com.miui.securitycore
adb shell pm install-existing com.miui.nextpay
adb shell pm install-existing com.miui.mediaviewer
adb shell pm install-existing com.miui.carlink
adb shell pm install-existing com.xiaomi.xmsf
adb shell pm install-existing com.xiaomi.phone
adb shell pm install-existing com.miui.voiceassist
adb shell pm install-existing com.xiaomi.micloud.sdk
adb shell pm install-existing com.miui.micloudsync
adb shell pm install-existing com.miui.touchassistant
adb shell pm install-existing com.miui.analytics
adb shell pm install-existing com.xiaomi.account
adb shell pm install-existing com.miui.thirdappassistant
adb shell pm install-existing com.miui.mishare.connectivity
adb shell pm install-existing com.miui.aod
adb shell pm install-existing com.xiaomi.payment
adb shell pm install-existing com.xiaomi.mi_connect_service
adb shell pm install-existing com.miui.uireporter
adb shell pm install-existing com.xiaomi.simactivate.service
adb shell pm install-existing com.miui.personalassistant
adb shell pm install-existing com.android.browser
adb shell pm install-existing com.miui.greenguard
adb shell pm install-existing com.miui.guardprovider
adb shell pm install-existing com.miui.cloudbackup
adb shell pm install-existing com.miui.contentcatcher
adb shell pm install-existing com.xiaomi.macro
adb shell pm install-existing com.xiaomi.aicr
adb shell pm install-existing com.miui.phrase
adb shell pm install-existing com.miui.extraphoto
adb shell pm install-existing com.bsp.catchlog
adb shell pm install-existing com.miui.securityadd
adb shell pm install-existing com.miui.systemAdSolution
adb shell pm install-existing com.miui.core
adb shell pm install-existing com.miui.dmregservice
adb shell pm install-existing com.miui.accessibility
adb shell pm install-existing com.xiaomi.digitalkey
adb shell pm install-existing com.miui.contentextension
adb shell pm install-existing com.xiaomi.mis
adb shell pm install-existing com.xiaomi.finddevice
adb shell pm install-existing com.xiaomi.xmsfkeeper
adb shell pm install-existing com.miui.notification
adb shell pm install-existing com.xiaomi.location.fused
adb shell pm install-existing com.xiaomi.aireco
adb shell pm install-existing com.miui.bugreport
adb shell pm install-existing com.miui.yellowpage
adb shell pm install-existing com.xiaomi.aiasst.service
adb shell pm install-existing com.xiaomi.ab
adb shell pm install-existing com.miui.misightservice
adb shell pm install-existing com.miui.vsimcore
adb shell pm install-existing com.miui.hybrid
adb shell pm install-existing com.xiaomi.market
adb shell pm install-existing com.miui.backup
adb shell pm install-existing com.android.fileexplorer
adb shell pm install-existing com.xiaomi.barrage
adb shell pm install-existing com.android.contacts
adb shell pm install-existing com.xiaomi.mirror
adb shell pm install-existing com.miui.voicetrigger
adb shell pm install-existing com.xiaomi.gamecenter.sdk.service
adb shell pm install-existing com.android.mms
adb shell pm install-existing com.xiaomi.aiasst.vision
adb shell pm install-existing com.android.quicksearchbox
adb shell pm install-existing com.xiaomi.mtb
adb shell pm install-existing com.miui.cloudservice
adb shell pm install-existing com.milink.service
adb shell pm install-existing com.miui.otaprovision
adb shell pm install-existing com.xiaomi.misettings
adb shell pm install-existing com.unionpay.tsmservice.mi
adb shell pm install-existing com.miui.newhome
adb shell pm install-existing com.miui.securityinputmethod
